### PR TITLE
[WIP]: ADDED Feature Upload from Web Link

### LINKED ISSUE #1: Bootstrap breaks on incorrect jquery version
Bootstrap requires jquery version >1.9 and < 3.0 . Since the bower.json lists jquery as `"latest"` it breaks.

### PR DESCRIPTION
**Pull request by mohdsanadzakirizvi**
This pull request adds a **new feature `upload using web link` to OpenPicker**. The following changes are implemented in this pull request : 

+ GruntFile is updated to contain new source files
+ README is updated 
+ app_defaults.coffee is updated to add new channel
+ added backend apis in `fetch_image` and `fetch_file`
+ uploads.coffee and appconfig.coffee is updated to get the `TEMPORARY_DIRECTORY` address
+ app_routes is updated with new routes
+ Added new files in angularjs controllers
+ updated `options_service`
+ `web.coffee` is now updated to serve `TEMPORARY_DIRECTORY` and its contents as `public` 
+ `bower.json` is updated to use `ONLY jquery v2.2.2` because Bootstrap breaks if v<=1.9 or >=3.0
+ `package.json` is updated with a new dependency .
+ various frontend views are updated and new ones created.
+ `usage.html.ejs` is updated to accomodate the new feature.
+ beautified UI of `web link`

### CODE REVIEW

File: app/javascript/angularapps/openpicker/controllers/fetched_image_preview_controller.js [hunk 1]
```diff
@@ -0,0 +1,54 @@
+ FetchedImagePreviewController = function($scope, $timeout, $http, DataAccessService, $sce, $filter, $location, Upload, OptionsService, LogService) {
```
Comment (gauravtiwari5050) [inline app/javascript/angularapps/openpicker/controllers/fetched_image_preview_controller.js]: Let us call this FetchedFilePreviewController

Comment (mohdsanadzakirizvi) [reply app/javascript/angularapps/openpicker/controllers/fetched_image_preview_controller.js]: Done. All views , controllers and code related to preview is now called `FilePreview`

**Comment by mohdsanadzakirizvi** [comment]
This pull request adds a **new feature `upload using web link` to OpenPicker**. The following changes are implemented in this pull request : 

+ GruntFile is updated to contain new source files
+ README is updated 
+ app_defaults.coffee is updated to add new channel
+ added backend apis in `fetch_image` and `fetch_file`
+ uploads.coffee and appconfig.coffee is updated to get the `TEMPORARY_DIRECTORY` address
+ app_routes is updated with new routes
+ Added new files in angularjs controllers
+ updated `options_service`
+ `web.coffee` is now updated to serve `TEMPORARY_DIRECTORY` and its contents as `public` 
+ `bower.json` is updated to use `ONLY jquery v2.2.2` because Bootstrap breaks if v<=1.9 or >=3.0
+ `package.json` is updated with a new dependency .
+ various frontend views are updated and new ones created.
+ `usage.html.ejs` is updated to accomodate the new feature.

File: app/api/web/fetch_file.coffee [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+appconfig = require('../../config/appconfig').appconfig
+fs = require('fs')
+request = require('request')
+csrf = require('csurf')
+async = require('async')
+prettysize = require('prettysize')
+path = require('path')
+tmpDir = appconfig.getTemporaryDirectory()
+fileLimits = appconfig.getFileLimits()
+filestores = {}
```
Comment (gauravtiwari5050) [inline app/api/web/fetch_file.coffee]: unsused variable

File: app/api/web/fetch_file.coffee [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+mimeRegex = /.(avi|wmv|flv|mpg|3gp|mkv|mp4|mpeg|mpeg-1|mpeg-2|mpeg-3|mpeg-4|mp3|wav|xlsx?|zip|7z|docx?|pptx?|pdf)$/i
```
Comment (gauravtiwari5050) [inline app/api/web/fetch_file.coffee]: can we make this go in a configuration file or read this optionally from the setting files
We can have default list to fallback on.

File: app/api/web/fetch_file.coffee [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+
+exports.init = (app) ->
+	
+	app.post '/fetch/', csrf({ cookie:true }), (req,res) ->
+		#check request came
+		console.log "Request recieved"
```
Comment (gauravtiwari5050) [inline app/api/web/fetch_file.coffee]: remove unneccessary logs

File: app/api/web/fetch_file.coffee [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+		#set file name from req.body
+		fileName = path.basename(req.body.url)
```
Comment (gauravtiwari5050) [inline app/api/web/fetch_file.coffee:20]: null checks ?

File: app/api/web/fetch_file.coffee [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+			dataSize = 0
+			request(reqURL,{method : 'HEAD'}, (err, res) ->
+				if err
+					console.error err
+					responseObject =
+						error: true
+						message: err.message
+					callback(null)
+				else
+					console.log "got headers"
```
Comment (gauravtiwari5050) [inline app/api/web/fetch_file.coffee]: unneccessary logs

File: app/api/web/fetch_image.coffee [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+fs = require('fs')
+request = require('request')
+csrf = require('csurf')
+async = require('async')
+prettysize = require('prettysize')
+path = require('path')
+tmpDir = appconfig.getTemporaryDirectory()
+fileLimits = appconfig.getFileLimits()
+filestores = {}
+imageRegex = /.(jpe?g|png|gif)$/i
```
Comment (gauravtiwari5050) [inline app/api/web/fetch_image.coffee]: move this to a config setting

File: app/api/web/fetch_image.coffee [hunk 8]
```diff
@@ -0,0 +1,91 @@
...
+
+exports.init = (app) ->
+	
+	app.post '/fetch/image', csrf({ cookie:true }), (req,res) ->
```
Comment (gauravtiwari5050) [inline app/api/web/fetch_image.coffee]: Merge image and file fetch endpoints

File: app/javascript/angularapps/openpicker/controllers/fetched_file_preview_controller.js [hunk 9]
```diff
@@ -0,0 +1,66 @@
+ FetchedFilePreviewController = function($scope, $timeout, $http, DataAccessService, $sce, $filter, $location, Upload, OptionsService, LogService) {
```
Comment (gauravtiwari5050) [inline app/javascript/angularapps/openpicker/controllers/fetched_file_preview_controller.js]: remove unused factories

File: app/javascript/angularapps/openpicker/controllers/web_link_controller.js [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+
+
+
+ };
+
+ WebLinkController.prototype.setupScopeMethods = function() {
+     var self = this;
+     self.scope.fetch = function() {
+        
+         self.scope.showLoader = true;
```
Comment (gauravtiwari5050) [inline app/javascript/angularapps/openpicker/controllers/web_link_controller.js:19]: Move this to a seperate functions;

File: app/api/web/fetch_file.coffee (hunk 5 above)
Comment (mohdsanadzakirizvi) [reply app/api/web/fetch_file.coffee:20]: `basename(..)` always extracts the _last part of the url_, so unless the url is **null** , the fileName won't be null. The **url can't be null** at this point because its being checked at the **form and frontend level**.

File: app/api/web/fetch_image.coffee (hunk 8 above)
Comment (mohdsanadzakirizvi) [reply app/api/web/fetch_image.coffee]: Done

File: app/javascript/angularapps/openpicker/controllers/fetched_file_preview_controller.js (hunk 9 above)
Comment (mohdsanadzakirizvi) [reply app/javascript/angularapps/openpicker/controllers/fetched_file_preview_controller.js]: Done

File: app/api/web/fetch_file.coffee (hunk 2 above)
Comment (mohdsanadzakirizvi) [reply app/api/web/fetch_file.coffee]: Done

File: app/api/web/fetch_file.coffee (hunk 4 above)
Comment (mohdsanadzakirizvi) [reply app/api/web/fetch_file.coffee]: Removed all console.logs since currently don't have a way to find the context of the log.

File: app/api/web/fetch_file.coffee (hunk 6 above)
Comment (mohdsanadzakirizvi) [reply app/api/web/fetch_file.coffee]: Removed all console.logs since currently don't have a way to find the context of the log.

File: app/javascript/angularapps/openpicker/controllers/web_link_controller.js (hunk 10 above)
Comment (mohdsanadzakirizvi) [reply app/javascript/angularapps/openpicker/controllers/web_link_controller.js:19]: Done. Now the **view logic** and the **controller logic** is seperate in `web_link_controller.js`

File: app/javascript/angularapps/openpicker/controllers/fetched_file_preview_controller.js (hunk 9 above)
Comment (mohdsanadzakirizvi) [inline app/javascript/angularapps/openpicker/controllers/fetched_file_preview_controller.js]: Done.

File: app/api/web/fetch_file.coffee (hunk 3 above)
Comment (mohdsanadzakirizvi) [reply app/api/web/fetch_file.coffee]: Done.

File: app/api/web/fetch_image.coffee (hunk 7 above)
Comment (mohdsanadzakirizvi) [reply app/api/web/fetch_image.coffee]: Done.

File: app/api/web/fetch_file.coffee [hunk 11]
```diff
@@ -0,0 +1,87 @@
...
+	app.post '/fetch/', csrf({ cookie:true }), (req,res) ->
+
+		#set file name from req.body
+		fileName = path.basename(req.body.url)
+		#Remove unnecessary characters and spaces in the file
+		fileName = fileName.replace(/@[^0-9a-z\.]+@i/g, "-")
+		fileName = fileName.replace(/\ +/g, "-")
+		#give file a unique id ending with the file name , provided it has one.
+		fileName = "#{util.uniqueId()}-#{fileName}"
+		reqURL = [req.body.url]
```
Comment (mohdsanadzakirizvi) [inline app/api/web/fetch_file.coffee:26]: @gauravtiwari5050 I need your review here. Here the url of the target image is converted to an array in order to use `async.each`. Because we need the *response to be sent **only** when the **entire fetching and writing process is complete***. Please give suggestion for code improvement, if any.
